version: "3"
services:
  web:
    build: .
    ports: 
      - "3000:3000"
    environment:
      - ADMIN_PASSWORD
      - FLAG
      - NODE_ENV
  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: